---
title: 'Estimating Confidence Intervals for CATE in Target Sample: Simulation Results'
author: "Carly Lupton Brantner"
date: '2023-09-05'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Combining Simulation Results

```{r, message=F}
library(tidyverse)
```

```{r, eval=F}
#read in all files
setwd("~/Desktop/Cluster/OOSEst/26Sep2023")
files <- list.files(pattern=".Rdata")

all <- c()
for (i in 1:length(files)) {
  load(file = files[i])
  all <- bind_rows(all, results[["all_res"]])
  print(i)
}

#checking output
seeds <- strsplit(files,"_") %>% map_chr(.f=function(x) x[2])
length(unique(seeds)) == length(files) #making sure every iteration has a unique seed

nrow(all) #to make sure every iteration ran
setwd("~/Dropbox/Moderation/Out of Sample Prediction/Data")
saveRDS(all, "all_results_26Sep2023.RDS")
```

```{r, message=F, warning=F}
all <- readRDS("Data/all_results_26Sep2023.RDS")

#long form for boxplot
all_long <- all %>%
  pivot_longer(cols = manual_res:tb_res,
               names_to = "Method",
               values_to = "Value") %>%
  mutate(scenario = paste(covars_fix, covars_rand, lin, eps_study_m,
                          eps_study_tau, eps_study_inter, sep = "_"),
         sds = paste(eps_study_m, eps_study_tau, eps_study_inter, sep = "_"))

#average across iterations
all_avg <- all %>%
  group_by(Metric, K, n_mean, n_sd, n_target, covars_fix, covars_rand,
           lin, eps_study_m, eps_study_tau, eps_study_inter,
           distribution, target_dist) %>%
  summarise(across(manual_res:tb_res, list(mean = mean, sd = sd)),
            n_iter = n())
summary(all_avg$n_iter) #check iterations
```

## Age Moderator, Same Target Distribution, Same Training Distributions

### Target CI Coverage

```{r, fig.height=7, fig.width=10}
#age, same target distribution
all_long %>%
  filter(Metric == "target_coverage", covars_fix == "age",
         target_dist == "same", distribution == "same") %>%
  ggplot(aes(x=sds, y=Value)) +
  geom_boxplot(aes(color = Method)) +
  geom_hline(aes(yintercept=.95), linetype = "dashed") +
  facet_wrap(~lin) +
  scale_y_continuous(labels = scales::percent, limits = c(.75, 1)) +
  labs(color="Method") +
  theme(axis.text.x = element_text(angle=90),
        text = element_text(size=12)) +
  xlab("Variability of Main, Trt, and Trt*Age Coefficients") +
  ylab("CI Coverage Percent in Target Sample") +
  ggtitle("Same Target Distribution")
```

### Training CI Coverage

```{r, fig.height=7, fig.width=10}
#age, same target distribution
all_long %>%
  filter(Metric == "train_coverage", covars_fix == "age",
         target_dist == "same", distribution == "same") %>%
  ggplot(aes(x=sds, y=Value)) +
  geom_boxplot(aes(color = Method)) +
  geom_hline(aes(yintercept=.95), linetype = "dashed") +
  facet_wrap(~lin) +
  scale_y_continuous(labels = scales::percent, limits = c(.75, 1)) +
  labs(color="Method") +
  theme(axis.text.x = element_text(angle=90),
        text = element_text(size=12)) +
  xlab("Variability of Main, Trt, and Trt*Age Coefficients") +
  ylab("CI Coverage Percent in Training Sample") +
  ggtitle("Same Target Distribution")
```

### Target CI Length

```{r, fig.height=7, fig.width=10}
#age, same target distribution
all_long %>%
  filter(Metric == "target_length", covars_fix == "age",
         target_dist == "same", distribution == "same") %>%
  ggplot(aes(x=sds, y=Value)) +
  geom_boxplot(aes(color = Method)) +
  facet_wrap(~lin) + ylim(0,10) +
  labs(color="Method") +
  theme(axis.text.x = element_text(angle=90),
        text = element_text(size=12)) +
  xlab("Variability of Main, Trt, and Trt*Age Coefficients") +
  ylab("CI Length in Target Sample") +
  ggtitle("Same Target Distribution")
```

## Target CI Coverage

```{r, fig.height=10}
#age, same target distribution
all_long %>%
  filter(Metric == "target_coverage", covars_fix == "age",
         target_dist == "same") %>%
  ggplot(aes(x=sds, y=Value)) +
  geom_boxplot(aes(color = Method)) +
  geom_hline(aes(yintercept=.95), linetype = "dashed") +
  facet_grid(lin~distribution) +
  scale_y_continuous(labels = scales::percent, limits = c(.75, 1)) +
  labs(color="Method") +
  theme(axis.text.x = element_text(angle=90),
        text = element_text(size=12)) +
  xlab("Variability of Main, Trt, and Trt*Age Coefficients") +
  ylab("CI Coverage Percent in Target Sample") +
  ggtitle("Same Target Distribution")
```

```{r}
#age, different target distribution
all_long %>%
  filter(Metric == "target_coverage", covars_fix == "age",
         target_dist == "different") %>%
  ggplot(aes(x=sds, y=Value)) +
  geom_boxplot(aes(color = Method)) +
  geom_hline(aes(yintercept=.95), linetype = "dashed") +
  facet_grid(lin~distribution) +
  scale_y_continuous(labels = scales::percent, limits = c(.75, 1)) +
  labs(color="Method") +
  theme(axis.text.x = element_text(angle=90),
        text = element_text(size=12)) +
  xlab("Variability of Main, Trt, and Trt*Age Coefficients") +
  ylab("CI Coverage Percent in Target Sample") +
  ggtitle("Different Target Distribution")
```

```{r}
#age2, same target distribution
all_long %>%
  filter(Metric == "target_coverage", covars_fix == "age2, sex",
         target_dist == "same") %>%
  ggplot(aes(x=sds, y=Value)) +
  geom_boxplot(aes(color = Method)) +
  geom_hline(aes(yintercept=.95), linetype = "dashed") +
  facet_grid(lin~distribution) +
  scale_y_continuous(labels = scales::percent, limits = c(.75, 1)) +
  labs(color="Method") +
  theme(axis.text.x = element_text(angle=90),
        text = element_text(size=12)) +
  xlab("Variability of Main, Trt, and Trt*Age Coefficients") +
  ylab("CI Coverage Percent in Target Sample") +
  ggtitle("Same Target Distribution, Age2")
```

```{r, eval=F}
all_long %>%
  filter(Metric == "target_coverage", covars_fix == "age, madrs",
         target_dist == "same") %>%
  ggplot(aes(x=sds, y=Value)) +
  geom_boxplot(aes(color = Method)) +
  geom_hline(aes(yintercept=.95), linetype = "dashed") +
  facet_grid(lin~distribution) +
  scale_y_continuous(labels = scales::percent, limits = c(.75, 1)) +
  labs(color="Method") +
  theme(axis.text.x = element_text(angle=90),
        text = element_text(size=12)) +
  xlab("Variability of Main, Trt, and Trt*Age Coefficients") +
  ylab("CI Coverage Percent in Target Sample") +
  ggtitle("Same Target Distribution, Age and MADRS")
```


## Training CI Coverage

```{r}
#age, same target distribution
all_long %>%
  filter(Metric == "train_coverage", covars_fix == "age",
         target_dist == "same") %>%
  ggplot(aes(x=sds, y=Value)) +
  geom_boxplot(aes(color = Method)) +
  geom_hline(aes(yintercept=.95), linetype = "dashed") +
  facet_grid(lin~distribution) +
  scale_y_continuous(labels = scales::percent, limits = c(.75, 1)) +
  labs(color="Method") +
  theme(axis.text.x = element_text(angle=90),
        text = element_text(size=12)) +
  xlab("Variability of Main, Trt, and Trt*Age Coefficients") +
  ylab("CI Coverage Percent in Training Sample") +
  ggtitle("Same Target Distribution")
```

### CI Coverage by Variance

NEED TO UPDATE (9/6)

```{r, eval=F}
#same target dist, same training dist
all_long %>%
  filter(Metric == "target_coverage",
         target_dist == "same",
         model != "GLHT",
         distribution == "same") %>%
  ggplot(aes(x=factor(eps_study_age), y=Mean, group=Method, color=spec)) +
  geom_jitter(aes(shape=model), size=2.5, width=.2, height=0) +
  facet_grid(eps_study_tau~eps_study_m) +
  scale_y_continuous(labels = scales::percent) +
  theme(axis.text.x = element_text(angle = 90)) +
  xlab("Variability Trt*Age Coefficients") +
  ylab("CI Coverage Percent in Target Sample") +
  ggtitle("Same Target Distribution and Same Training Distribution")
```


## Target CI Length

```{r}
#plot target ci length
#same target dist
all_long %>%
  filter(Metric == "target_length", covars_fix == "age",
         target_dist == "same") %>%
  ggplot(aes(x=sds, y=Value)) +
  geom_boxplot(aes(color = Method)) +
  ylim(0, 10) +
  facet_grid(lin~distribution) +
  labs(color="Method") + 
  theme(axis.text.x = element_text(angle=90),
        text = element_text(size=12)) +
  xlab("Variability of Main, Trt, and Trt*Age Coefficients") +
  ylab("CI Length in Target Sample") +
  ggtitle("Same Target Distribution")
```

## Target MSE

NEED TO UPDATE (9/6)

```{r, eval=F}
#plot target mse
#same target dist
all_long %>%
  filter(Metric == "target_mse",
         target_dist == "same",
         covars_fix == "age") %>%
  ggplot(aes(x=sds, y=Value, group=Method, color=Method)) +
  geom_boxplot() + ylim(0,5) +
  facet_grid(lin~distribution) +
  theme(axis.text.x = element_text(angle = 90)) +
  xlab("Variability of Trt and Trt*Age Coefficients") +
  ylab("MSE in Target Sample") +
  ggtitle("Same Target Distribution")

#different target dist
all_long %>%
  filter(Metric == "target_mse",
         target_dist == "different",
         covars_fix == "age") %>%
  ggplot(aes(x=sds, y=Value, group=Method, color=Method)) +
  geom_boxplot() + ylim(0,5) +
  facet_grid(lin~distribution) +
  theme(axis.text.x = element_text(angle = 90)) +
  xlab("Variability of Trt and Trt*Age Coefficients") +
  ylab("MSE in Target Sample") +
  ggtitle("Different Target Distribution")
```




